import '../game/models/tile_type.dart';

class ThaanaHelpers {
  static const Map<String, String> uiTextEn = {
    'app_name': 'Akuru Drop',
    'play': 'Play',
    'settings': 'Settings',
    'shop': 'Shop',
    'levels': 'Levels',
    'score': 'Score',
    'moves': 'Moves',
    'time': 'Time',
    'target': 'Target',
    'pause': 'Pause',
    'resume': 'Resume',
    'restart': 'Restart',
    'quit': 'Quit',
    'level_complete': 'Level Complete!',
    'level_failed': 'Out of Moves!',
    'next_level': 'Next Level',
    'retry': 'Retry',
    'level_select': 'Level Select',
    'watch_ad_moves': 'Watch ad for 5 extra moves',
    'watch_ad_coins': 'Watch ad for 2x coins',
    'buy_moves': 'Use 100 coins for 5 extra moves',
    'daily_reward': 'Daily Reward',
    'coins': 'Coins',
    'sound': 'Sound',
    'music': 'Music',
    'notifications': 'Notifications',
    'language': 'Language',
    'rate_app': 'Rate App',
    'privacy_policy': 'Privacy Policy',
    'about': 'About',
    'extra_moves': 'Extra Moves',
    'shuffle': 'Shuffle',
    'remove_tile': 'Remove Tile',
    'word_bonus': 'Word Bonus!',
    'combo': 'Combo',
    'no_more_moves': 'No more moves! Shuffling...',
  };

  static const Map<String, String> uiTextDv = {
    'app_name': 'އަކުރު ޑްރޮޕް',
    'play': 'ކުޅޭ',
    'settings': 'ސެޓިންގްސް',
    'shop': 'ފިހާރަ',
    'levels': 'ލެވެލްތައް',
    'score': 'ސްކޯ',
    'moves': 'މޫވްސް',
    'time': 'ވަގުތު',
    'target': 'ޓާގެޓް',
    'pause': 'މަޑުކުރޭ',
    'resume': 'ކުރިއަށް ގެންދޭ',
    'restart': 'އަލުން ފަށާ',
    'quit': 'ނުކުމޭ',
    'level_complete': '!ލެވެލް ފުރިހަމަ',
    'level_failed': '!މޫވްސް ހުސްވެއްޖެ',
    'next_level': 'ދެން އޮތް ލެވެލް',
    'retry': 'އަލުން ކުޅޭ',
    'level_select': 'ލެވެލް ޚިޔާރުކުރޭ',
    'watch_ad_moves': 'އިތުރު 5 މޫވް ހޯދަން އެޑް ބަލާ',
    'watch_ad_coins': '2x ލާރި ހޯދަން އެޑް ބަލާ',
    'buy_moves': '100 ލާރިން 5 މޫވް ގަނެ',
    'daily_reward': 'ދުވަހުގެ އިނާމު',
    'coins': 'ލާރި',
    'sound': 'އަޑު',
    'music': 'މިއުޒިކް',
    'notifications': 'ނޮޓިފިކޭޝަން',
    'language': 'ބަސް',
    'rate_app': 'އެޕް ރޭޓް ކުރޭ',
    'privacy_policy': 'ޕްރައިވެސީ ޕޮލިސީ',
    'about': 'ތަޢާރަފް',
    'extra_moves': 'އިތުރު މޫވްސް',
    'shuffle': 'އެއްކޮށްލާ',
    'remove_tile': 'ޓައިލް ނަގާ',
    'word_bonus': '!ބަސް ބޯނަސް',
    'combo': 'ކޮމްބޯ',
    'no_more_moves': '...ޝަފުލް ކުރަނީ',
  };

  static String getText(String key, {bool dhivehi = false}) {
    final map = dhivehi ? uiTextDv : uiTextEn;
    return map[key] ?? key;
  }
}
